#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition main			### specify partition name where to run a job. main: all nodes; gtx1080: 1080 gpu card nodes; rtx2080: 2080 nodes; teslap100: p100 nodes; titanrtx: titan nodes
#SBATCH --time 0-10:30:00			### limit the time of job running. Make sure it is not greater than the partition time limit!! Format: D-H:MM:SS
#SBATCH --job-name rl211_nd_test_%a			### name of the job
#SBATCH --output logs/job-%A-%a.out			### output log for running job - %J for job number
#SBATCH --mail-user=noamsi@post.bgu.ac.il	### user's email for sending job status messages
#SBATCH --mail-type=ALL			### conditions for sending the email. ALL,BEGIN,END,FAIL, REQUEU, NONE

#SBATCH --gres=gpu:1				### number of GPUs, allocating more than 1 requires IT team's permission
#SBATCH --mem=60G				### ammount of RAM memory, allocating more than 60G requires IT team's permission
#SBATCH --cpus-per-task=6			### number of CPU cores, allocating more than 10G requires IT team's permission

#SBATCH --array=0-2

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "\nSLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST
echo -e "\nSLURM_ARRAY_TASK_ID:\t\t" $SLURM_ARRAY_TASK_ID "\n\n"


### Start your code below here ####
prob=$(printf %.1f "$(($SLURM_ARRAY_TASK_ID))e-1")
module load anaconda				### load anaconda module (must be present when working with conda environments)
source activate rl211				### activate a conda environment, replace my_env with your conda environment
echo -e "\nprob:\t" $prob
python RL211_HW5_V1.py -p $prob

